---
title: "CUES Distinguished Fellowship Nomination"
author:
- Dr. Ryan Straight (ryanstraight\@email.arizona.edu)
- Assistant Professor, Educational Technology
subtitle: Project Proposal
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Project Proposal

As a CUES Distinguished Fellow, I propose to further develop and expand a small-scale project that I have led over the past three years: the implementation of a ubiquitous online collaboration tool (Slack) as a collaborative community and instructional hub. (See the Catalyst grant referenced below.) As both local and national trends reveal rapid growth in online course enrollment^[https://www.insidehighered.com/news/2017/05/02/report-finds-growth-volatility-online-education-market], the Grand Challenge this proposal addresses is the creation and development of community among students, faculty, and staff, with the goal of fostering positive and productive working relationships, as well as promoting inquiry, motivation to learn, collaboration, and engagement in virtual learning environments. Given the rapid shift from traditional to blended and fully online learning environments, the obligation to address, develop, and foster community and discourse in virtual spaces is of paramount importance (Benade, 2015). One of the most difficult aspects of teaching and learning online is the relative lack of community and sense of belonging felt by students and instructors, alike (Yuan & Kim, 2014). Two decades into the 21st century, many online learning programs continue to confuse remote learning with isolated learning, creating an experience oddly reminiscent of the correspondence schools of the last century. With ever increasing demand for and enrollment in online programs, there is no better time than the present to move beyond simply providing quality content to learners, into designing collaborative learning spaces for all members of the learning community – students, faculty, and staff alike -- exploiting the potential of online environments to facilitate mutual inquiry, dialogue, and the creation of knowledge through constructive social processes.

Students don’t choose a program based on the learning management system they will use or the instructional design method followed by their instructor. Instead, they trust their instructors to be experts, who will ensure that they will have the opportunity to learn effectively and efficiently in an authentic and engaging online environment. That said, absent dialogue, collaboration, and community, the quality of online learning suffers, leaving students with a dissatisfying and ultimately inadequate experience – regardless of the instructor’s expertise or the quality of the content (Williams & Lahman, 2011). The proposed project is designed to prevent such unfortunate outcomes, providing a ready means by which to foster community and promote collaboration and engagement. The use of Slack is intended to serve as an adjunct to other forms of online communication and collaboration. While instruction may take place within Slack, and for my classes it often does, Slack is not meant to serve as a replacement for synchronous classes and live discussions. Nor is it meant solely to replace the asynchronous discussion forum in the LMS (though it can be used to do so). Instead, the learning community will use Slack as home base, allowing them to meet, collaborate, and engage in dialogue related to various aspects of online learning: In Slack, what might have otherwise been a days-long email chain or awkward asynchronous discussion, can happen in minutes as natural conversation, whether via text chat (an option frequently appreciated by students with social anxiety) or by jumping into a video or audio call. What might have been six different versions of a document floating between co-authors is now a centralized document with multiple active collaborators. Instead of students waiting, hoping a classmate looks at a discussion forum, there is now a sense of live, real-time presence.

Paraphrasing one of my students, “When I get online and see your ‘Active’ status dot, it’s like peeking down the hallway and seeing your office door cracked open. I know I can poke my head in and that feels great.” This feeling has been echoed numerous times since I began using Slack in my courses. It is incredibly difficult to understate the importance of this fundamental fact: The online experience is dramatically different from the in-person experience. Online learning has the potential to bring the world to students and bring students into a world of community – but only if the affordances of the medium are properly exploited. Treating online learning platforms as simple content delivery systems, however, is a misuse of the technology and a failure to leverage the medium to its greatest advantage.

One simple way to better leverage the medium is to promote community. Speaking on the topic of “belongingness” in online classes, Dr. Blower lamented in a 2018 CUES presentation: “Online, I can’t figure out how to do that [promote a sense of belonging]. Yet.^[http://streaming.oia.arizona.edu/clientFlashABR/play.php?clipname=/perm/cues/cues_fellow_101718/web.smil&align=left&autoplay=off&help=on&aspect=wide]" This project aims to move yet into the present, providing students, instructors, and staff an easily accessible and intuitive online community space, using industry-standard tools repurposed for education. While Slack can be used for a variety of academic purposes, including discourse, project collaboration, and peer review, it is a multi-purpose platform, widely used in business and industry, that students will likely encounter again in their professional careers. Therefore, use of Slack as outlined in this proposal presents numerous advantages.

Furthermore, as a CUES Distinguished Fellow, I will work to develop and promote workshops designed to help faculty learn more about building community in online and hybrid courses and programs (or simply maintaining community beyond the brick-and-mortar classroom). I will also work with the CUES Director to determine what form of Broader Engagement would be most beneficial to the university at large and to the CUES program’s future. This could be in collaboration with the Office of Instruction and Assessment, as they currently provide small workshops on community building, as well.

## Proposed Activities or Methods

This project is designed to answer the question, "How best can we improve learning through a sense of belonging and community, specifically in fully online and hybrid programs at distance?" The proposed answer to this, based within and beyond the Community of Practice framework (Wenger, 1999; Wenger & Snyder, 2000), is the development of a large online community that includes faculty, staff, and students, leveraging "participation, engagement, interaction, creativity and cohesion" (Tsiotakis & Jimoyiannis, 2015, p. 47). Ideally, the project will run for three years. Each semester, the goal would be to on-board a new entity, be that program/instructor, department, student group, et cetera. Three years is appropriate because of the relatively unique 2+2 system at the distance campus network. As we offer Bachelor of Applied Science degrees, the vast majority of our students come from a Community College. As such, they typically spend two years with us, making efficient community-building a priority. This project also potentially presents an opportunity to carve even deeper partnerships with local community colleges to extend the University community beyond the 2+2 window.

A three-year project would ensure that by the third year as many UA South students as possible in the programs that have joined in with the project will both enter _and leave_ having been immersed the entire time, providing the consistency, presence, and persistence crucial to successful learning in online contexts (Joksimovic & Gaševic, 2015). If possible, keeping these alumni within the community to build more ties between current and former students is also preferable. My main focus in the project will be to work with other instructors and program directors to bring them into the community and determine how best to serve their students. A number of faculty have expressed their interest in moving in the direction of this project but also expressed a lack of available time or resources. This project is aimed at addressing those roadblocks by providing a scalable and efficient framework for inclusion. Main benchmarks for this transition will be the number of those entities and students added to the team. A growth of roughly 100 users annually is the target. Pre- and post-semester surveys will be administered to instructors and students to determine how better to improve the culture and effectiveness of the team and strengthen the community of practice.

This is in large part a continuation of previous, small-scale and exploratory research of my own that has been presented locally (Straight, 2016) and nationally (Straight, 2017), both specifically with Slack as the selected tool and generally as an exploration of contemporary means of building distance community online. One goal of this proposed project is to expand the scale at which the benefits and affordances of this community- and belongingness-building ecosystem can be offered and systematically explored going forward. It is my contention that an ecosystem such as this (though possibly not *exactly* this, which the project is also designed to determine) will supplant previous iterations such as online forums did to email and email did to bulletin boards. 


## History, Details, and Justification of Chosen Tool

The tool by which this project hopes to succeed in increasing a sense of belonging and community is Slack. Mostly known in business, Slack is a team communication tool intended to streamline community and build a transparent knowledge base. I began using Slack in my online classes in 2015 and, as it became a successful method of instruction and communication, led me to co-write a grant to bring it to other instructors that wished to use it. Our Slack team was established in April of 2016 for use in the following fall semester. In that first semester, we had 54 actively daily users and the peak daily messages reached 350 (Sept 22, 2016). As of April 16, 2019, we have 169 daily active users and a peak daily messages of 1,953 (April 10, 2019). Total members is now at 770. Total messages sent since Wednesday, April 13, 2016: 177,641. Clearly, it has become a tremendous communication hub. 

This is not limited to purely academic discussions. In a small survey of our UA South Slack team participants in 2018 (N=50), 64% of students reported that they either use the Slack team to communicate with others in non-class-related ways or expressed a desire to begin. Programs using the Slack team at UA South include Educational Technology, Informatics, Cyber Operations, Network Operations, Computer Science, and English. Other Slack teams across campus include the Veteran Student Center, UX\@UA, UITS, the Office of Digital Learning, and programs in Optics, Law, Public Health IT, Engineering, RDI, CAPLA, AIS, Housing and Residential Life, Integrative Medicine, and more. Slack's grassroots growth at the university, combined with this project, may serve as the justification for engaging in a full-campus solution, bringing the possibility of community evidenced within these examples to the study body at large. This falls within Pillar 2 of the Strategic Plan as it seeks to build "culture founded on interdisciplinary collaboration and are committed to do together what no individual department or faculty member can do alone.^[https://arizona.app.box.com/s/di3hlmppfkg05j9xohzowa3sku7eq9vu]"

As in our own Slack team, the initial on-boarding and first impression of the culture is key to students' successful and persistent use of the tool to collaborate (Küçüka, 2010). As such, I will be working summers to develop comprehensive best practices, on-boarding, and support documentation--based on my experience as team administrator for the last 3 years and feedback from students and other instructors--for programs and offices that wish to on-board. I will continue to improve upon and expand these materials, bringing them to larger audiences, such as at conferences or summits. These include but are not limited to hypermedia text documents, screencasts, and customizing a question-and-answer automated bot inside the Slack team to answer questions, should anyone have them^[https://get.slack.help/hc/en-us/articles/202026038-An-introduction-to-Slackbot]. This is no small venture, as the kinds of support and instruction needed by a staff office is wholly different from that needed by an instructor wishing to move class communication into the program. While some support materials have been developed (connecting D2L to Slack, automating channel enrollment, et cetera), a much more comprehensive guide is necessary. This guide may also be useful outside the university as the kind of methodology and material other universities may wish to have for themselves, reaffirming and seeking to solidify the University of Arizona as a bleeding-edge online education innovation incubator as we move into 2020.

During the project period, UA South will be transitioning to a "college model" (name TBD). During this transition, the faculty in "shared" programs (those offered at both the main campus and the distance campuses; Psychology and English, for example) will be returning to their main campus "homes" while continuing to be offered at distance campuses. This opportunity would allow us to bring this community-building methodology to an even larger audience, potentially serving as the impetus and springboard for a full-campus adoption. This also benefits students in Arizona Online, in which nearly all of UA South programs are offered. Having this Slack team--or a federation of them, interconnected through shared channels--aims to create communities of practice and improve teaching and social presence within participating programs with transparency and genuineness.

\newpage

# References

_References are shared throughout the proposal, scholarship, and budget documents._

Anderson, T., Rourke, L., Garrison, D. R., Archer, W. (2001). Assessing Teaching presence in a Computer Conference Environment. *Journal of asynchronous learning networks*, *5*(2), 1-17.

Benade, L. (2015). Bits, Bytes and Dinosaurs: using Levinas and Freire to address the concept of ‘twenty-first century learning’, *Educational Philosophy and Theory*, *47*(9), 935-948. https://doi.org/10.1080/00131857.2015.1035159

Gunder, A., Knott, J., & Straight, R. (2018). #SquadGoalsNetwork - Remixing the Personal Learning Network. Presented at the *2018 OLC Accelerate conference*, Orlando, FL.

Joksimovic, S., & Gaševic, D. (2015). Social presence in online discussions as a process predictor of academic performance. *Journal of Computer Assisted Learning*, 31, 638–654. https://doi.org/10.1111/jcal.12107

Küçüka, M. (2010). Lurking in online asynchronous discussion. *Procedia - Social and Behavioral Sciences*, *2*(2), 2260–2263. https://doi.org/10.1016/j.sbspro.2010.03.319

Shah-Nelson, C., Gunder, A., Stewart, J., Romanoski, M. Knott, J., Scragg, B., & Straight, R. (2018). With a Little Help From My Friends: The Power of the PLN. Winner of the Effective Practice Award. Presented at the *2018 OLC Accelerate conference*, Orlando, FL.

Straight, R. (2019). The New Professor: How I Podcasted My Way Into Students’ Lives (And How You Can, Too). Selected Best In Track. Presented at the *2019 OLC Innovate conference*, Denver, CO.

Straight, R., Gunder, A., Stewart, J., King de Ramirez, C., Thompson, K., & Pizzo, J. And We’re Live! A Rough Guide on Academic Podcasting. Presented at the *2018 OLC Accelerate conference*, Orlando, FL.

Straight, R. (2017). Slacking Off in Class: Cloud-Based Team Collaboration in Online Higher Education Programs. Presented as an Innovation Lab at the *2017 OLC Innovate conference*, New Orleans, LA.

Straight, R. (2016). Slack and the Online Classroom. Presented at the *2016 University of Arizona IT Summit*, Tucson, AZ.

Straight, R. & Gunder, A. (2016). Innovative Learning Projects: Promoting Leading-Edge Opportunities in Higher Education. Poster presented at the *2016 University of Arizona IT Summit*, Tucson, AZ.

Tsiotakis, P., & Jimoyiannis, A. (2016). Internet and Higher Education Critical factors towards analysing teachers’ presence in on-line learning communities. *The Internet and Higher Education*, 28, 45–58. https://doi.org/10.1016/j.iheduc.2015.09.002

Wenger, E. (1999). *Communities of practice: Learning, meaning, and identity*. Cambridge university press.

Wenger, E. C., & Snyder, W. M. (2000). Communities of practice: The organizational frontier. *Harvard business review*, *78*(1), 139-146.

Williams, L. & Lahman, M. (2011).  Online Discussion, Student Engagement, and Critical Thinking, *Journal of Political Science Education*, *7*(2), 143-162. https://doi.org/10.1080/15512169.2011.564919

Yuan, J. and Kim, C. (2014). Development of online learning communities. *Journal of Computer Assisted Learning*, *30*, 220-232. https://doi.org/10.1111/jcal.12042

