---
title: October 2018 SGN Social Media Takeover
author: ryan
date: '2018-10-01'
#slug: october-2018-sgn-social-media-takeover
categories:
  - Professional
tags:
  - squad goals network
  - social media
  - halloween
  - fear
subtitle: ''
summary: 'I amtaking over the social media accounts for the [Squad Goals Network](https://squadgoalsnetwork.com) this month and it is gonna get _spooky_.'
authors: []
lastmod: '2019-06-13T11:38:40-07:00'
featured: no
image:
  caption: '[Via Dan Burton on Unsplash](https://unsplash.com/photos/tJuF_siTxJw)'
  focal_point: ''
  preview_only: no
projects: ["squad-goals-network"]
---
As such, I wanted to share a little bit about the concept, the process, the expectations, and the theme of the month. The sheer organization, thoughtfulness, and inclusion of last month's takeover by [Angela Gunder](http://angelagunder.com/) means there are some pretty high standards for this month. That was in part the reason for this month's theme: **fear**. Fun theme, right? Right? I mean, I've even got one of the _Silent Hill_ game soundtracks on while I write this. I'm 100% committed to this theme, I'm tellin' ya.

So, why fear? Simple: we all experience it and we best overcome it with help from our support systems, and what is a network like SGN at its core if not a support system? We share thoughts to clarify them, we collaborate to produce ideas and results that we never could've achieved on our own (synergy, basically, but that word has been robbed of all impact over the years, I think), and we quite literally just ask each other for help sometimes. 

One of the reasons I'm so glad to have been included in this network of brilliance (constellation, remember?) is that I'm usually pretty bad about connecting with people. I'm terrible with names, I'll fall off the face of the planet for weeks or months at a time as I obsess with something new, and my memory is almost completely overrun with random facts in place of useful things like details about the people in my life. A group like SGN goes a long way to helping me either deal with, remedy, or overcome those shortfalls. 

Part of overcoming fear is admitting one's shortcomings to begin with. While I often think of and paint myself as a non-standard kind of academic (hence _The New Professor_, my podcast), I recognize that I'm far from perfect and have many, many realms of improvement I can (and should) venture into. For some, like myself, even admitting that can be scary. It's not like it's a secret; nobody's perfect. It's about acknowledging that imperfect as areas for growth, not permanent and irreparable flaws. I sometimes feel we think of ourselves as marble statues, hoping to put on display the most perfect version of ourselves: polished, impressive, towering. Then when we make mistakes or simply fail at something, that patina of perfection is marred in some way that we just know someone is going to notice and it will permanently alter and diminish the persona we've so carefully sculpted. 

As I get older and learn more and more than I know less and less about the world, it occurs to me that we're not made of marble at all. We're simply clay. We can be remolded and repaired, improved on and changed. This also makes us vulnerable as the wrong person can come along and take a chunk out of you. That's where having a network, whether it's a personal learning network or a support network comes in (though, as I said, I'd venture to say they're often one and the same): not only do your friends and family and colleagues help you repair that damage, whatever it may be, but they help you become a better version of yourself. And that's what we should all be striving for, after all.

And that's what this month is all about, for me, at least: acknowledging our fears, admitting we all make mistakes and sometimes fail despite our best efforts, and understanding that _that's okay_. When students tell me they're anxious about a defense, for example, I always say the same thing: that means you care. Fear can be a great motivator if you let it be, if you can accept it as a hurdle to overcome rather than a door being shut.

This month, I'd like you to share with me and the rest of the squad what you're afraid of and, if we can, we can work on it together. Also, I make absolutely no apologies for the massive number of Halloween puns and jokes that I'll be making this month. I'm a Halloween baby and it's creeped into the very fabric of my being. So, join the [Squad Ghouls Network](https://twitter.com/sqdglsntwrk) (see?) for a month of acknowledging, admitting, and overcoming your fears.
