baseURL: "https://tiagoboldt.net"
languageCode: "en"
DefaultContentLanguage: "en"
title: "Tiago Boldt Sousa"
theme: "anatole"
summarylength: 100
enableEmoji: true
enableRobotsTXT: true

# Google Analytics
googleAnalytics: "UA-245030-9"

# Syntax highlighting
pygmentsUseClasses: true
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true

markup:
  highlight:
    style: monokai
