# Configuration of Academic
# Documentation: https://sourcethemes.com/academic/
#
# This file is formatted using TOML syntax - learn more at https://learnxinyminutes.com/docs/toml/
# Each configuration section is defined by a name in square brackets (e.g. `[outputs]`).

# Title of your site
title = "Rudra Murthy"

# The URL of your site.
# End your URL with a `/` trailing slash, e.g. `https://example.com/`.
baseurl = "https://murthyrudra.github.io/"

# Enter a copyright notice to display in the site footer.
# To display a copyright symbol, type `&copy;`.
copyright = ""

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""

# Enable comments by entering your Disqus shortname
disqusShortname = ""

############################
## Advanced options below ##
############################

# Name of Academic theme folder in `themes/`.
theme = "academic"

# Get last modified date for content from Git?
enableGitInfo = true

# Default language to use (if you setup multilingual support)
defaultContentLanguage = "en"
hasCJKLanguage = false  # Set `true` for Chinese/Japanese/Korean languages.
defaultContentLanguageInSubdir = false

paginate = 10  # Number of items per page in paginated lists.
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true


[outputs]
  home = [ "HTML", "CSS", "RSS", "JSON" ]
  section = [ "HTML", "RSS" ]

# Configure BlackFriday Markdown rendering.
#   See: https://gohugo.io/getting-started/configuration/#configure-blackfriday
[blackfriday]
  hrefTargetBlank = true  # `true` opens external links in a new tab. See https://github.com/gohugoio/hugo/issues/2424
	angledQuotes = false
	latexDashes = true
  extensions = ["backslashLineBreak"]

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"

[author]
  name = "Rudra Murthy V"
  # bio = "Super bio with markdown support **COOL**"
  job = "PhD Student"
  location = "Mumbai, India"
  # Your Gravatar email. Overwrite `author.picture` everywhere in the blog
  # gravatarEmail = "rudra@cse.iitb.ac.in"
  # Your profile picture
  # Overwritten by your gravatar image if `author.gravatarEmail` is filled
  picture = "/img/profile.jpg"
  # Your Twitter username without the @. E.g : thibaudlepretre
  twitter = "rudramurthyv"
  # Your google plus profile id. E.g : +ThibaudLepretre or 114625208755123718311
