# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Dettagli"
  url = "/details"
  weight = 10

[[main]]
  name = "News"
  url = "/post"
  weight = 12

[[main]]
  name = "Iscrizione"
  url = "/register"
  weight = 14

[[main]]
  name = "Regole"
  url = "/rules"
  weight = 40

[[main]]
  name = "Edizioni passate"
  url = "/past_editions"
  weight = 50

[[main]]
  name = "Stato neve"
  url = "/snow"
  weight = 60

[[main]]
  name = "Contatti"
  url = "/contact"
  weight = 80

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
