appearance:
  mode: system
  color: emerald

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: Software Engineer
    org_name: Nguyen Thanh Huy
    description: 'Nguyen Thanh Huy’s personal website – backend software engineer specializing in .NET, microservices, system architecture, and high-performance backend systems.'
    twitter: ''
  analytics:
    google_analytics: 'G-7PZ31MEMJK'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: false
    show_theme_chooser: true
    logo:
      text: "Nguyen Thanh Huy"

footer:
  copyright:
    notice: '© {year} Nguyen Thanh Huy. Some rights reserved under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

features:
  math:
    enable: false
  privacy_pack:
    enable: false
