# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: dark
day_night: false
font: 'appnavi'
font_size: L

# SEO

site_type: Organization
local_business_type: ''
org_name: 'アプリNavi'
description: '大阪府立大学の部活アプリNaviのブログです。部員がプログラミング関連の記事を投稿しています。'
twitter: ''

# Contact (edit or remove options as required)

email: ''
phone: ''
address:
  street: 学園町1番1号 A5棟
  city: 堺市
  region: 大阪府
  postcode: '5998531'
  country: 日本
  country_code: ja
coordinates:
  latitude: '34.547818'
  longitude: '135.505782'
directions: ''
office_hours: []
appointment_url: ''
contact_links:
  - icon: twitter
    icon_pack: fab
    name: Twitter
    link: 'https://twitter.com/OPUAppNavi'
  - icon: line
    icon_pack: fab
    name: LINE Openchat
    line: https://line.me/ti/g2/WmwnmlbJNN6U5F9ZKhO3tg?utm_source=invitation&utm_medium=link_copy&utm_campaign=default
  - icon: envelope
    icon_pack: fas
    name: Email
    link: 'mailto:contact@opuappnavi.com'
  - icon: laptop
    icon_pack: fas
    name: Web Site
    link: 'https://opuappnavi.com/#/'

# Site header

main_menu:
  enable: true
  align: r
  show_logo: true
  show_language: false
  show_day_night: false
  show_search: true
  highlight_active_link: true

# Localization

date_format: '2006/01/02'
time_format: '15:04'
address_format: ja
# Site features

highlight: true
highlight_languages:
  - r
highlight_style: qtcreator_dark
math: true
diagram: true
privacy_pack: false
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false
show_related:
  book: true
  page: false
  post: true
  project: true
  publication: true
  event: true
reading_time: false
section_pager: true
docs_section_pager: true
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'This work is licensed under {license}'
abstract_length: 135
plugins_js:
  - custom
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 3
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: true
comments:
  provider: ''
  commentable:
    post: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: mapnik
  api_key: ''
  zoom: 20
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: master
  local_backend: false
icon:
  pack:
    ai: true
