# Appearance
appearance:
  mode: system
  color: emerald

extensions:
  decap_cms:
    branch: main


# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: Software Engineer
    org_name: Nguyen Thanh Huy
    description: 'Trang web cá nhân của Nguyễn Thanh Huy - Kỹ sư phần mềm backend chuyên về .NET, hệ thống phân tán và phát triển hệ thống hiệu suất cao.'
    twitter: ''
  analytics:
    google_analytics: 'G-7PZ31MEMJK'  # bạn có thể thêm mã GA nếu dùng
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: ''
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    blox: "navbar"
    fixed_to_top: true
    show_search: false
    show_theme_chooser: true
    logo:
      text: "Nguyễn Thanh Huy"

# Site footer
footer:
  copyright:
    notice: '© {year} Nguyễn Thanh Huy. Một số quyền được bảo lưu theo {license}'
    license:
      enable: true
      allow_derivatives: true
      share_alike: true
      allow_commercial: true

# Localization
locale:
  date_format: '2 Jan 2006'
  time_format: '15:04'

# # Site features
# features:
#   math:
#     enable: false
#   privacy_pack:
#     enable: false


# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/HugoBlox/hugo-blox-builder/'
    content_dir: starters/blog/content
    branch: main
  comment:
    # Choose a provider: giscus, disqus, commento, or '' to disable commenting
    provider: 'giscus'
    giscus:
      repo: 'YoungBirds134/theme-academic-cv'
      repo_id: 'R_kgDOOv6MXA'
      category: 'General'
      category_id: 'DIC_kwDOOv6MXM4CqmsT'
      theme: catppuccin_mocha
      language_code: vi
      mapping: pathname
      loading: lazy
