# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  theme_day: coffee
  theme_night: dark 
  day_night: true
  font: Cyberpunk
  font_size: m

# SEO

marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    description: 'The personal webpage for Mohammad A. Noureddine'
  analytics:
    google_analytics: 'UA-154900366-1'

# Site header

header:
  navbar:
    enable: true
    align: l
    show_log: true
    show_language: false
    show_day_night: true
    show_search: true
    highlight_active_link: true

# Site footer

footer:
  copyright:
    notice: '© {year} Mohammad A. Noureddine'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization

locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'
  address_format: en-us

# Site features
features:
  syntax_highlighter:
    enable: true
    theme_light: github-light
    theme_dark: dracula

  math:
    enable: true

  diagram:
    enable: true

  avatar:
    gravatar: false
    shape: circle

  # TODO: check when to enable this feature
  privacy_pack:
    enable: false

  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false

  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''

  map:
    provider: ''
    api_key: ''
    zoom: 15

# Security
security:
  allow_frame: false 

# Extensions

extensions:
  cms:
    branch: master
    local_backend: false
  academicicons:
    enable: true

###############################################################################
# OLD STUFF FROM PREVIOUS BUILD
###############################################################################

# email: noureddi@rose-hulman.edu
# phone: 888 888 88 88
# address:
#   street: Moench F214
#   # city: Terre Haute
#   # region: IN 
#   # postcode: '47803'
#   # country: United States
#   # country_code: US
# appointment_url: 'https://calendly.com/mnoureddine/'
# # contact_links:
# #   - icon: twitter
# #     icon_pack: fab
# #     name: DM Me
# #     link: 'https://twitter.com/Twitter'
# #   - icon: skype
# #     icon_pack: fab
# #     name: Skype Me
# #     link: 'skype:echo123?call'
# #   - icon: keybase
# #     icon_pack: fab
# #     name: Chat on Keybase
# #     link: 'https://keybase.io/'
# #   - icon: comments
# #     icon_pack: fas
# #     name: Discuss on Forum
# #     link: 'https://discourse.gohugo.io'

# # Localization

# # Site features

# reading_time: true
# section_pager: false
# docs_section_pager: true
# sharing: true

# abstract_length: 135
# plugins_js: []
# publications:
#   date_format: January 2006
#   citation_style: apa
# projects:
#   post_view: 2
#   publication_view: 2
#   talk_view: 2
# breadcrumb:
#   page_types:
#     book: true
#     enable: true

