before_install:
- sudo apt-get update -qq
- sudo apt-get install -y pandoc
- sudo apt-get install -y texlive-full
- sudo apt-get install -y texlive-xetex
- chmod u+x ./travis/build.sh
- chmod u+x ./travis/publish.sh
script: "./travis/build.sh"
after_success:
- "./travis/publish.sh"
env:
  global:
  - GH_USER_NAME: apazaf
  - GH_PROJECT_NAME: gbpn
  - GIT_AUTHOR_NAME: Travis
  - GIT_AUTHOR_EMAIL: noreply@travis-ci.org
  - RESULT_PDF_PATH=$TRAVIS_BUILD_DIR/content/rules/gbpn-rules.pdf
  - TZ="Europe/Rome"
  - secure: mZUO7xdbJSUjAT/7U+Bcyin+Q1waDVr5B9vO3GcNSVj0Cl8oHMMnXaDtwM0voltReJ/3640Yt8MjTwjt/hK/WXpvh5vZwmb1nO7doWhYcrPSuFmmQa4qioEENpJG2yw8caVibmMfFhnEFFbNprin4ma2qNbWekKqgqe1ZWZNc25OubFWvrfJ4PMr6fvYam4TMr++v9NlCZWN9L5quUlS6Y3kuxlylMF/KYhZU1Q06dUqFmnuKyfcHxDU+ASpbfNkALzDVCfiSFL12orD3fmEd2kV80I4VNcHlHNf7pGw9Zpvn9JrfLZOX+xbIF9EwzVQosntXr1h4apBDYdO/IAGJ5pQSkQ1EKBvyMSEYcyD2NYRyLsq90+IyQiWlBg8eUbvsW2Deb+9ZFs1HtfCupopkTdZ+es7/fknoInGrVFAmtISP9GuU5gEijfVTWjAfcE9Jw8OxGwSjc0O7aLr77kt3v0s6oT+voQ/vww7uaS1/Nt6PWwxHUEyhttqS3ZkmHKtKgvYLO8XmOyuCzFEJ1wlguO41dgCfAZN1+hbhbHfHtGoA8UO+4Xuz2D4LtbSb4M65adNU6ocAH9goq/K0aN1qS9OFaZOkq0h7ao4YLEl+CSMmJKvCWYz4BwRVIay+8Pj0o6mzAyDUErCpMix6tLKdBqpMAp73B4dLYf/i7v9ne8=
