---
title: Finding Order in Chaos
author: ryan
date: '2018-11-02'
#slug: finding-order-in-chaos
categories:
  - Professional
tags:
  - reflection
  - teaching
  - chaos
  - organization
  - semantic annotation
  - mediawiki
subtitle: ''
summary: ''
authors: []
lastmod: '2018-11-02T16:44:29-07:00'
featured: no
image:
  caption: '[Photo by Clint Adair on Unsplash](https://unsplash.com/photos/BW0vK-FA3eg)'
  focal_point: ''
  preview_only: no
projects: []
---

I don't want to say I'm the *typical* professor (heck, I have [an entire podcast devoted to exploring just what the heck that means](https://thenewprofessor.com)) but I certainly do occasionally resemble the clichéd *absent-minded professor*. Remember: good thoughts are clear thoughts and that's much harder than it sounds when your job is to think about so much, so often, for so long.

To put it simply, we have a lot of stuff in our heads. In my experience, one of the most difficult and daunting aspects of working in a primarily intellectual field is nothing more than the organization of thoughts and ideas. We're confronted with new ideas, questions, corrections, updates, improvements, alterations, and retractions nearly every day as we learn more and more about virtually everything. So the question becomes: if we're not superhuman, how do we keep track?

I suppose you could make it your priority to spend the entirety of your time and energy on memorizing the minutiae of everything but, let's face it, we're not all cut out for that kind of perfect recall. I, for one, need to keep notes or I just _forget_. Maybe you're the same. But then the question becomes: where do you keep them? How do you organize them? How much do you automate and how much do you update? Whether it's your reading notes on one particular scholar's *ouvre* or a little reminder to add a particular resource to an assignment for a class, we (normally) can't just keep all that in our heads. I know some people, like the prolific Raul Pacheco-Vega, that use physical bucket-style collections (in his case, the "Everything Notebook"). Others create hundreds or thousands of Google Documents or giant Scrivener projects. The important part is that it works *for them*.

It took me a very, very long time to figure out a system that a) is sustainable, b) I'll actually use, and c) is designed in a way that mirrors (or at least generally reflects) the way my thought processes work. I tried virtually every organizational paradigm out there, from the Evernote-style bucket to physical notebooks (and, I have to say, I'm devastated that physical notebooks don't do it for me because I _love_ them and own many, many blank ones). What I discovered is, beyond all that, that I love creating systems. What I love less than that is _maintaining_ them. So, my job became to find a system that I felt like I was creating _all the time_, something malleable, something always growing and improving, and something within which I could automate the more mundane tasks.

If you've listened to [episode 19 of The New Professor](https://thenewprofessor.com/019/), you already know what I'm going to say next: for me, even though it may sound like a lot of work, the best environment to off-load information and ideas is a **[Semantic MediaWiki](https://www.semantic-mediawiki.org/)**. If you want to know exactly how I do that or what it looks like... you'll have to wait on another post. (I've been keeping the wiki for nearly a decade and created a three-part series on how to set one up back in, probably, 2009 but that's *long* gone.)

So watch for those posts. Hopefully they can be of help to you. (Whenever they get here.)
