---
title: Evidence
author: ryan
date: '2018-08-24'
#slug: evidence
categories:
  - Personal
tags:
  - evidence
  - nutrition
  - read watch woof
subtitle: ''
summary: ''
authors: []
lastmod: '2018-08-24T09:40:23-07:00'
featured: no
image:
  caption: '[Photo by Anton Darius | \@theSollers on Unsplash](https://unsplash.com/photos/pqoNaY73NAY)'
  focal_point: ''
  preview_only: no
projects: []
---
I've decided to start placing the *Read* portion of the [**Read, Watch, Woof**]({{< ref "/project/read-watch-woof/index.md" >}}) newsletters in the blog. So, while you can get the writing part of it, you'll miss the dogs and the video if you're not signed up. Jus' sayin'. So here's a piece about evidence and being willing to change your mind.

***

It's the first week of fall semester and there is *much* going on, as you can imagine. I know some of you dear readers are in the same academic boat as I am, so know that *you are seen*.

Lately, I've been thinking a lot about **evidence**. Not evidence in the Forensic Files sense (side note: have you noticed that a television channel called *Escape* shows almost 24-7 "true crime" shows? what on earth does that say about us?) but in the how-we-make-the-best-decisions-in-an-attempt-to-live-our-best-lives sense. In this case, it's actually about living our *longest* lives. I'll explain. (And add a caveat that I am *not* an expert in nutrition; just somebody who really likes bacon but also really likes bread dipped in olive oil, which explains my weakness for Carbonara.)

## Let's talk about carbohydrates

A few weeks ago-ish, I wrote a bit about going "low-carb." Since then, a study was released that is the largest of its sort ever published. It's not perfect by any means (no study ever is and if anyone claims otherwise they're trying to sell you something) but the results seem to support (pro-tip when talking about research: be wary of using absolutes like "confirm" or "prove") the notion of All Things in Moderation. Turns out, according to the study, that going low-carb can actually shave years off your life. Turns out, the best diet is one that's *balanced* and *spread out*, meaning doesn't eschew one macronutrient entirely for another and actively seeks out variety. They say the ideal percentage of carbohydrates is about 50-55%. Should probably aim for the same protein-to-lean-mass ratio as usual, and then supplement with fat to reach your caloric goal. 

It seems the "Eat food, not too much, mostly plants" adage isn't far off. Does that mean everybody needs to go vegan? Of course not. But it really does suggest something closer to the Mediterranean diet is pretty ideal. At least now I have an excuse to buy that insanely expensive bottle of olive oil!

So, while I stand by my assertion that you should do what works for you, specifically, in concert with advice from your physician, this is simply more information that you can use to make an informed decision (along with your doctor).  See? Evidence. That's the nature of being a skeptic and trusting in the scientific method: when new evidence that is gathered genuinely and presented with fidelity and neutrality goes against previous evidence (or, in many cases, assumptions), it's important to incorporate that into your decision making without prejudice or embarrassment. Evidenced-based *anything* is more likely to be beneficial than choices made based on whims or spurious assertions. 

## Growth, and I'm not just talking about my waistline (...stupid carbs)

This brings us to evidence more broadly. I'm a firm believer in evidence-based policies, decisions, anything, really. Having said that, it is in our nature to conflate and incorporate our ideas, likes, and decisions (regardless of their premises) with our senses of *self*. Ever gotten in an argument with someone about a band that they think is just *a-ma-zing* and you simply don't see it? And they take it personally? Your dislike of their favorite thing is converted into a dislike of *them*. This is something I'm certain we've all experienced on both sides. (I will argue all night about whether *Dark Side of the Moon* is the most perfect album of all time. Spoiler: it absolutely is.) This kind of internalization can be hugely damaging to both a healthy sense of identity and rational public discourse. I'll simply point you toward any Facebook comment thread that devolves into a shouting match and personal insults because of something even remotely resembling a political stance.

We need to overcome this. We need to be better at separating our opinions from our identities. We need to learn again how to grow, admit past mistakes, and see an update to our thinking upon the presentation of new evidence as a *virtue* rather than an admittance of fault. We are works-in-progress and should be thrilled when we get to make that progress, regardless of how it happens. In a video game, if you improve your character based on something you learn in-game or a mechanic you start understanding better, do you project embarrassment onto the character because they hadn't been doing that all along? Would it even make sense to reject that new knowledge simply because it conflicts with an existing view? No. That would be lunacy. A self-imposed handicap, hamstringing yourself for the sake of pride. So why would we do that in reality?

I find it much more human to update your convictions and expand your thinking on a topic when presented with new information than to dig your heels in and resist simply because it means disagreeing with your past self. In politics, a change in position is often referred to as flip-flopping, but this is entirely different. If your position is that penguins live solely in the Great Lakes region of North America and, upon being presented with evidence that no, in fact, they're from the southern hemisphere and do not actually spend any time with polar bears, you change your position about penguin habitat locations... that is not flip-flopping. That's correcting a faulty assumption. We need more of that.

Evidence gathered genuinely and presented without ulterior motive should not be seen as a threat or a personal attack on someone that held contradictory views. It should be accepted, reviewed, scrutinized, and incorporated in an existing body of evidence and used to make better, more informed decisions about our lives and the world at large.

I guess that's a long way of saying I'm eating bread again. 
