---
---
## Course Schedule

The general course schedule is maintained in detail in the LMS. Recorded class sessions are also available there. Attending class sessions (or watching the recorded session if you missed class) and submitting your notes to the appropriate weekly dropbox is **absolutely necessary and vital** to your success in this class.

For the purposes of this class, weeks begin on MONDAY.

---

## Communication

I am nearly always available through electronic means. My policy is that I will respond *usually* immediately, *mostly* within 24 hours, and  *at the latest* to questions within 48 hours (or by Monday morning if sent during the weekend, during which I do not work). If I do not respond in this windows do not hesitate to bug me. All questions that are class-related and not personal in nature should be posted in Slack to the class channel so everyone can benefit from the response (or chime in). Personal issues may be sent via direct message (DM). **All** emails sent to me should have subjects beginning with **INFV ###** or **ETCV ###**. All emails I send (that are not automatically created by the LMS) will have the same. This makes finding things considerably easier. Still, I reiterate: Slack is the better way to contact me. 

Also note that I do not respond to communications about making up missed work or improving grades during the end of the semester. It is your responsibility to keep an eye on your grade throughout the semester and contact me with your concerns before the course is nearly ended. If you missed some points in week 2 you should not be petitioning me in week 7 to make them up.

---

## Course Technology

This is a technology-driven course. As such, you are required to have ready access to a relatively modern computer and an account that allows you to install software on that computer. You should also *be excited* to try and use new technologies. We do a lot of that.

The course website can be found on D2L at [https://d2l.arizona.edu/](https://d2l.arizona.edu/). Log in with your NetID. Note that course content lives primarily within D2L but usually as Google Documents that require you to use your UA account to access. Keep this in mind if you use multiple Gmail accounts.

We will have a full-class chatroom/discussion board/forum on [Slack](https://uasouth.slack.com). You will be able to log into Slack via your Google Apps for Education account (it will use WebAuth). **Having the Slack application installed on your phone is required** (if possible).

Updating your profiles in both D2L and Slack is **required**. We’re spending a lot of time together, so no excuse to just be a NetID for 16 weeks. Picture, likes and dislikes, job title, degree, home campus, the works.

You may be asked to use software that requires more processing power than your computer has. Contact the instructor if you feel this will prevent you from participating.

Class meetings are hosted via Zoom. **It is REQUIRED that you have a microphone and headphones for the class meetings**. (A cheap set of earbuds will work if your laptop has a mic and you will be from a relatively quiet place.) **You _will be expected_ to use them**. Should we have a class activity that requires a microphone and you do not have one you *will not* receive credit for that assignment. Having working headphones and a microphone is **not negotiable**. 

You will need to install the latest edition of the [Chrome browser](https://www.google.com/chrome/browser/) for this class. Tech support is vastly simpler if everyone uses the same browser.

Document submissions are required to be in PDF format unless otherwise noted. Assignments should also be in APA 6th ed. formatting, which is best achieved using [Microsoft Word](http://uabookstore.arizona.edu/technology/campuslicensing/default.asp) (free for students) or Google Documents (free for all).

---

## Class Policies

These policies run across all of my classes. Take the time to read them if this is your first class with me (go ahead and read them again, even if it’s not). The following are in addition to or in concert with all policies found in the University Catalog: [http://catalog.arizona.edu/policies](http://catalog.arizona.edu/policies) 

## The 7.5 Week Semester

The material covered and assignments required in a shortened 7.5 week semester are equal to those in a full 16 week semester with half the time allotted. Time management and "working ahead" are practical necessities in an accelerated semester. **Do not fall behind**. “I didn’t have time” is not an acceptable excuse for missing assignments or readings. 

---

## Use of Student Work

Assignments completed for this course may be used as examples of student work in an instructor portfolio. Names and other identifying elements will be removed before inclusion. Students who do not wish their work to be used must inform the instructor in writing before the start of the second week of classes.

---

## Student Workload

According to UA policy, at least 15 contact hours of recitation, lecture, discussion, seminar, or colloquium, as well as a minimum of 30 hours of student homework are required for each unit of student credit. A contact hour is the equivalent of 50 minutes of class time or 60 minutes of independent-study work. For an online course this equates to 45 hours of work per credit; 135 hours total for the semester in a 3-credit class (9 hours per week). The hour requirements specified above represent minimums for average students, and considerable deviation (more or less) of these requirements may occur. **In shortened, accelerated 7.5 week classes this workload is doubled**. **_You should expect to spend 18 hours per week on this class. Budget your time wisely and always look ahead._**

[http://catalog.arizona.edu/policy/credit-definitions](http://catalog.arizona.edu/policy/credit-definitions) 

---

## Tutoring

UA South provides free tutoring for writing and math, and various other related subjects, at multiple locations and fully online. Students can access free tutoring in- person at our Cochise and Yuma County locations, at the UA Think Tank in Tucson, as well as fully online from the UA Think Tank.

To find tutoring hours and availability near you, please select your location below to find the tutoring available at your learning center.

+ [Sierra Vista & Douglas: http://www.cochise.edu/academic-support/tutoring/](http://www.cochise.edu/academic-support/tutoring/)
+ [Tucson: http://thinktank.arizona.edu/](http://thinktank.arizona.edu/)
+ [Yuma: https://www.azwestern.edu/student-success-center/tutoring](https://www.azwestern.edu/student-success-center/tutoring)
+ [All Locations (Online): http://thinktank.arizona.edu/online-tutoring](http://thinktank.arizona.edu/online-tutoring)

---

## Academic Dishonesty

Cheating and plagiarism are unethical. Students are expected to do their own work. Plagiarism includes copying or cutting and pasting from online sources, taking information from a book or article, copying someone else's paper, or having someone else do your work for you. Research sources must be properly documented. Students found cheating or intentionally plagiarizing will receive a zero for the assignment and may be dismissed from the class with a failing grade, required to attend workshops, have a permanent note included on his or her transcript, or any combination thereof to the instructor’s discretion.

I take this **very seriously** and, as professional academics in this field, I expect you to, as well. **When in doubt, cite!** See our program website for a primer on APA style, citation, and avoiding plagiarism and cheating.

In a development course like this it is likely you will come across much in the way of inspiration, be it in class or through your own research. Keep a constant log of all assets you either use in your work (free vectors or audio clips, for example) or note down what the inspiration was for a particular development choice. Being *inspired* by something you love is perfectly fine; simply *using* it is not.

---

## Plagiarism and Cheating

Integrity and ethical behavior are expected of every student in all academic work. This Academic Integrity principle stands for honesty in all class work, and ethical conduct in all labs and clinical assignments. This principle is furthered by the student Code of Conduct and disciplinary procedures established by ABOR Policies 5-308 through 5-404, all provisions of which apply to all University of Arizona students. This Code of Academic Integrity is intended to fulfill the requirement imposed by ABOR Policy 5-403.A.4 and otherwise to supplement the Student Code of Conduct as permitted by ABOR Policy 5-308.C.1. 

* Code of Academic Integrity: [https://deanofstudents.arizona.edu/policies-and-codes/code-academic-integrity](https://deanofstudents.arizona.edu/policies-and-codes/code-academic-integrity) 
* How to avoid plagiarism: [http://new.library.arizona.edu/research/citing/plagiarism](http://new.library.arizona.edu/research/citing/plagiarism) 

*As a blanket policy* I have automated plagiarism checking enabled for all assignments in all my classes. This is not meant to suggest I expect anyone to plagiarize but to demonstrate how seriously I take this.

---

## Threatening Behavior

The University seeks to promote a safe environment where students and employees may participate in the educational process without compromising their health, safety or welfare. The Arizona Board of Regents’ Student Code of Conduct, ABOR Policy 5-308, prohibits threats of physical harm to any member of the University community, including to one’s self. Threatening behavior can harm and disrupt the University, its community and its families. 

* Disruptive Behavior in an Instructional Setting: [http://policy.arizona.edu/education-and-student-affairs/disruptive-behavior-instructional-setting](http://policy.arizona.edu/education-and-student-affairs/disruptive-behavior-instructional-setting) 
* Disruptive Student Behavior policy: [https://deanofstudents.arizona.edu/accountability/disruptive-student-behavior](https://deanofstudents.arizona.edu/accountability/disruptive-student-behavior) 

There will always be times when electronic communication will be necessary between students and between instructor and students. Please treat each other kindly and professionally!

---

## Nondiscrimination and Anti-Harassment Policy

The University is committed to creating and maintaining an environment free of discrimination.  Our classroom is a place where everyone is encouraged to express well-formed opinions and their reasons for those opinions. We also want to create a tolerant and open environment where such opinions can be expressed without resorting to bullying or discrimination of others. 

* See: [http://policy.arizona.edu/human-resources/nondiscrimination-and-anti-harassment-policy](http://policy.arizona.edu/human-resources/nondiscrimination-and-anti-harassment-policy) 

---

## Attendance

You’re an adult -- be responsible for your attendance. Any absences **must** be addressed with the instructor prior to class except in emergencies. Missed classes may require a make-up assignment submitted for partial credit. There are also a number of things that you are expected to complete within the first week of class (these are listed clearly in the LMS). Failure to do these can result in being administratively dropped from the class. Likewise, no/poor attendance throughout the beginning of the class can result in being administratively dropped from the class. *Note: instructors are **_not_** obligated to administratively drop students for failure to participate.* If a student is administratively dropped between weeks five through eight a "W" will be administered if he/she has maintained a passing grade (60% or higher). An “E” will be administered for anything lower unless extenuating circumstances dictate otherwise as deemed appropriate by the instructor. See the class attendance policy in the General Catalog: [http://catalog.arizona.edu/policy/class-attendance-participation-and-administrative-drop](http://catalog.arizona.edu/policy/class-attendance-participation-and-administrative-drop)

---

## Paper/Assignment Submission

All assignments, papers, projects should be submitted in the specified method based on the *system time* in the class website. Due to the frantic nature of game development projects, **no late work will be accepted for partial points**. Keep in mind, however, that much work is iterative and **you are still expected to complete it as later assignments/work are predicated on earlier assignments/work**. Be aware that instructors **are not obligated** to accept late work at all. Students are responsible for ensuring proper delivery of their assignments/papers/projects. If an agreement has been made with the instructor to accept work after the due date or in a unique format it is **the student’s responsibility** to let the instructor know when this is done. Submissions of this nature may not necessarily be graded and returned along the same schedule as others. This policy may change for individual assignments. **Do not wait until the last minute to submit**. Your router going down or your computer’s clock being different from that of the LMS are **not** valid reasons for being late. It is also highly suggested you keep your ‘working’ folder in Google Drive or some other cloud-copy backup location like Box.net. Your University of Arizona Google Apps for Education account comes with free, unlimited storage. Use it. 

*All written assignments submitted should be properly formatted and stylized. I **_require_** that the American Psychological Association, 6^th^ ed, revised manual be followed. Period.*

---

## Grading Turn-Around Time

Please note that I generally do not begin to grade an assignment until on or after the due date since it is my preference to grade all students’ submissions at one time, as well as return grades and feedback simultaneously. I will do my best to provide grades and useful feedback expediently.

However, some submissions require me to spend a significant time working through the materials. This may cause me to be delayed in grading that project. Additionally, if I am traveling I may be delayed in grading your submission. If this happens I will let everyone know.

NOTE: You are expected to retain an electronic copy of all work submitted. If transmission of the work fails, you are expected to "resend" the document or message (in the case of online discussions). This is entirely your responsibility.

---

## Social Media Policy

Should this course require participation in social media you have the option of using "burner" accounts should you feel uncomfortable with using a personal account for academic work. You may even choose to use a unique, unrelated email account to sign up for various platforms. You are in no way required to follow, friend, etc., your instructor, only to provide information about the account you decided to use. 

The reason for this policy is as follows: if you are active on social media already and want to combine your personal and professional/academic activities, you may; if you are active on social media and *do not* want to mingle your personal and professional/academic activities, you have that option (this method is preferred for students); if you are *not* active on social media and have no intention of maintaining a presence after this course, simply abandon or delete your burner account. It is your instructor’s wish to reap the benefits of developing personal learning networks and getting global perspectives while maintaining a safe, secure environment for you.

*The exception to this rule: students in the Educational Technology program are required to joint the program’s LinkedIn group and "connect" to the program’s instructors.*

---

## Office Hours and Scheduling Meetings

I have a *virtual* open-door policy. That is to say, feel free to send me a DM and see if I’m available to chat any time. I like to think of it as dropping by the department’s building and peeking your head in my door. Just as it is in person, I’m not always available right that second, so you’re welcome to ‘wait in the hall’ (until I’ve finished doing whatever I was doing) or schedule an appointment with me. I’m happy to do a video conference via Slack (preferably), Zoom meet in person on Main Campus or in my office on the Pima East campus, as I live in Tucson. 

---

## Accessibility and Accommodations

If you have special needs as addressed by the Americans with Disabilities Act and need course materials in alternative formats or need any special accommodations, please notify your course instructor(s) and contact the Disability Resource Center immediately at 520-621-3268 or get information from DRC web site  [http://drc.arizona.edu](http://drc.arizona.edu).

---

## Basic Securities

Any student who has difficulty affording groceries or accessing sufficient food to eat every day, or who lacks a safe and stable place to live, and believes this may affect their performance in the course, is urged to contact the Dean of Students for support. Furthermore, please notify the professor if you are comfortable in doing so. This will enable them to provide any resources that they may possess. (Adapted from [Sara Goldrick-Rab](https://medium.com/@saragoldrickrab/basic-needs-security-and-the-syllabus-d24cc7afe8c9).)

---

## What to Expect

Given the nature of our field, it is entirely possible that materials considered adult, controversial, or objectionable in nature will crop up from time to time. We will be spending the majority of our time on the Internet and we should not only understand but respect the fact that it is a free and open place. As responsible adults, I encourage and expect everyone to be safe, smart, and secure when engaged online. Should you have any questions or concerns about content, please email me to discuss an alternative assignment.

---

## Non-Endorsement Policy

In the course of accessing the online resources available in this course you will encounter a number of advertisements.  We can not remove them from the material so it is your choice if you explore any of the advertising you encounter. However, the University does not endorse any of these advertisements.

---

## A Personal Note

We live in a digital age. We communicate through digital means. While I fully expect your submitted assignments to employ proper spelling, grammar, construction, and styling, I not only allow but expect and encourage you to express yourself using whatever communicative means you like. I will use emoticons; I will type in the text chat without using proper capitalization and punctuation; I will use ‘reaction gifs’ and make references to memes in casual situations; I will share entertaining but relevant media. If I can do it, so can you. Just remember: a place and time for everything, just as the way you speak with friends on a Friday night out is not the same as when you’re giving a conference presentation. Context is everything. 

*The contents of this syllabus are subject to on-going change over the course of the semester as needed to accommodate students’ progress. Always **link** to this document instead of downloading a local copy.*
