---
title: Educated vs Intelligent
author: ryan
date: '2018-07-06'
#slug: educated-vs-intelligent
categories:
  - Personal
tags:
  - The Diamond Age
  - quote
  - education
  - intelligence
subtitle: ''
summary: ''
authors: []
lastmod: '2018-07-06T09:05:12-07:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

>"Nell," the Constable continued, indicating through his tone of voice that the lesson was concluding, "the difference between ignorant and educated people is that the latter know more facts. But that has nothing to do with whether they are stupid or intelligent. The difference between stupid and intelligent people — and this is true whether or not they are well-educated — is that intelligent people can handle subtlety. They are not baffled by ambiguous or even contradictory situations — in fact, they expect them and are apt to become suspicious when things seem overly straightforward.

>"In your Primer you have a resource that will make you highly educated, but it will never make you intelligent. That comes from life. Your life up to this point has given you all of the experience you need to be intelligent but you have to think about those experiences. If you don't think about them, you'll be psychologically unwell. If you do think about them, you will become not merely educated but intelligent...."

[Stephenson, N. (2000). *The Diamond Age: or, A Young Lady's Illustrated Primer*. p. 256](https://amzn.to/2u9Qa3O)
