---
title: "CUES Distinguished Fellowship Nomination"
author:
- Dr. Ryan Straight (ryanstraight\@email.arizona.edu)
- Assistant Professor, Educational Technology
subtitle: Current or Past Scholarship or Innovation
output:
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

As a Career-Track faculty and dual program director with an 80% teaching and 20% service contract my time and support for research and publication is necessarily limited, demonstrating, I feel, the passion I have for this project. It stems directly from a co-authored Catalyst grant offered by the Classroom Technology Upgrade project. The "Innovation Grant" was designed to pay for the pilot use of Slack as an interdisciplinary, cross-program communication and community hub for UA South students within (but not limited to) the Educational Technology, Informatics, and Organizational Leadership programs. Scholarship that followed (ie, Straight, 2016 and Straight, 2017) revealed a marked improvement in student engagement, satisfaction, and feeling of community and belongingness compared to more "traditional" learning and communication management systems. I then later went on to write about the use of Slack in online programs for the *Chronicle of Higher Education*. This, in turn, led me to be offered the role of Social Media Advisor for the Chan Zuckerberg *Learning Science Research Nurturing Students & Classroom Innovation* (LRNSCI) project by the International Society for Technology in Education (ISTE).

It's my firm belief, supported by my own research and experience as well as Anderson, Rourke, Garrison, and Archer's (2001) _Community of Inquiry_ framework, that student success, satisfaction, and belongingness can be directly tied to authentic, genuine interaction with their instructors, other students, and the content. As such, my participation in and study of *personal learning networks* (PLNs), very closely tied with the current project, has also been award-winning (see Straight, 2019 and Shah-Nelson, Gunder, Stewart, Romanoski, Knott, Scragg, & Straight, 2018). We created a framework for building and maintaining PLNs (Gunder, Knott, & Straight, 2018) that draws on not just evidence-based methods but comes from a place of passion for learning and love of self and community. Based on this, we are in the process of co-authoring a book on the topic.

However, most closely tied to the current project is my position as the inaugural *Faculty Fellow*^[http://saem-aiss.arizona.edu/sr-vp/faculty-programs/faculty-fellows] for the UA South distance campus network, a position that also allows me to expand my teaching to first-year Honors students in a seminar titled *Cyborgs and Transhumanism*. In 2017, I was approached and asked to determine how to bring the Faculty Fellow mission (to "shrink" the large university experience into a more personal, more intimate small liberal arts college-like experience) for students spread across multiple campuses and even across the globe (as in the case of Arizona Online). The Faculty Fellows are a select group of innovative, caring faculty from across the institution, and I was honored to be asked. In part, one way for me to accomplish this was to renew a (then somewhat defunct) podcast and realign the content to fit the Fellows' goals. This has led me to present nationally on both the general idea of academic podcasting (Straight, Gunder, Stewart, King de Ramirez, Thompson, & Pizzo, 2018) and specifically on my own journey and experience (Straight, 2019), which also won an award. This also led to me being interviewed by Inside HigherEd's *Inside Digital Learning* (forthcoming) about how instead of bringing my disparate students to me, I decided to go _to them_ by means of podcasting. An evidence-based text resulting from this experience is also in the works.

Closer to home I have been an invited speaker on the topic of the future of educational technology at the TENWEST festival, a local event focusing on "the arts, social impact, STEM, entrepreneurship, technology, and sustainability." On a more local outreach level, I was also asked to speak at the Gridley Middle School to the parents of 6-8th grade students on STEM resources and career opportunities for their children. These events, especially, underscore the importance of being forward-thinking in terms of how we envision education, as, just as in the private sector, I believe the way today's 6th graders will learn when they reach our institution may be wholly unexpected. We should be doing all we can _today_ to prepare for them _tomorrow_.
