name: Build #and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.100.1
        TARGET_REPO: sfortz/sfortz.github.io
        TOKEN: ${{ secrets.ACCESS_SECRET }}
        CNAME: www.sfortz.github.io
