name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: sfortz/hugo-deploy-gh-pages@main
      env:
        HUGO_VERSION: 0.100.1
        TARGET_REPO: sfortz/sfortz.github.io
        TOKEN: ${{ secrets.ACCESS_SECRET }}
        CNAME: www.sfortz.github.io
