# Hugo Blox GitHub Action to convert Bibtex publications to Markdown-based webpages
name: Import Publications From Bibtex

# Require permission to create a PR
permissions:
  contents: write
  pull-requests: write

# Run workflow when a `.bib` file is added or updated in the `data/` folder
on:
  push:
    branches: ['dev']
    paths: ['bibtex/islab.bib']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  hugoblox:
    if: github.repository_owner != 'HugoBlox'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4
        with:
          ref: dev
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install academic==0.10.0
      - name: Run Academic (Bibtex To Markdown Converter)
        # Check `.bib` file exists for case when action runs on `.bib` deletion
        # Note GH only provides hashFiles func in `steps.if` context, not `jobs.if` context
        if: ${{ hashFiles('bibtex/islab.bib') != '' }}
        run: |
          cat bibtex/islab.bib | sed 's/\\underline{\(.*\)}/\1/g' > bibtex/temp.bib
          academic import bibtex/temp.bib content/en/publication/ --compact --overwrite
          academic import bibtex/temp.bib content/ja/publication/ --compact --overwrite
          rm bibtex/temp.bib
      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: ":robot: created pr to update publication"
          base: master
          branch: import-publications
          title: ":robot: automatic"
          token: ${{ secrets.GITHUB_TOKEN }}
